modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="MIT License"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Tom Wolf - for pushing me to do things I hate, so that I can play things I love. \\n Claycorp for helping my single cell make sense of all of this" #optional
authors="Heaser"
description='''
This tries to solve a long lasting issue of digging some blocks to put your pipes underground.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"